name: Github Actions Demo - Main
run-name: ${{ github.actor }} is testing out Github Actions
on:
  push: 
    branches: [main]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latests
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run:
        python -m pip  Install --upgrade pip
      
